DROP TABLE article IF EXISTS;
DROP TABLE product IF EXISTS;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE product
(
    id          INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price       INTEGER
);

CREATE UNIQUE INDEX users_unique_email_idx ON product (name);

CREATE TABLE article
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name       VARCHAR(255)       NOT NULL,
    content    VARCHAR(65535),
    created    DATE DEFAULT now() NOT NULL,
    product_id INTEGER            NOT NULL,
    FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);